name = "lean-riscv"
version = "0.1.0"
defaultTargets = ["run-riscv-lean"]

[[lean_lib]]
name = "LeanRiscv"

[[lean_exe]]
name = "run-riscv-lean"
root = "Main"

[[require]]
name = "ELFSage"
git = "https://github.com/GaloisInc/ELFSage.git"
rev = "e28bd859821b8d9b4831ebdfed3903c91b4096e5"

[[require]]
name = "Lean_RV64D_executable"
#git = "https://github.com/GaloisInc/sail-riscv.git"
#rev = "a4c8dfa84d17d0bbc577bf5c67ef098b2c1bed0a"
#subDir = "build/model/Lean_RV64D_executable"
# This can be useful for debugging (comment out the above three lines)
path = "../../../sail-riscv/build/model/Lean_RV64D_executable/"
