name = "lean-riscv"
version = "0.1.0"
defaultTargets = ["run-riscv-lean"]

[[lean_lib]]
name = "LeanRiscv"

[[lean_exe]]
name = "lean_emulator"
root = "Main"

[[require]]
name = "ELFSage"
git = "https://github.com/GaloisInc/ELFSage.git"
rev = "e28bd859821b8d9b4831ebdfed3903c91b4096e5"

[[require]]
name = "Lean_RV64D_executable"
path = "../build/model/Lean_RV64D_executable/"
